name: Sync Template Repository

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  sync-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2.5.1
        with:
          source_repo_path: conjikidow/repository-template
          upstream_branch: main
          pr_labels: 'automated,template-sync'
